import type { MatchOptions, MatchProfile } from "@shared/validation/github";
import {
  CONTRIBUTION_TYPES,
  DIFFICULTY_LEVELS,
  FALLBACK_LABELS,
} from "@shared/validation/github";

export {
  CONTRIBUTION_TYPES,
  DIFFICULTY_LEVELS,
  FALLBACK_LABELS,
};

export type { MatchOptions, MatchProfile };

export const DEFAULT_PROFILE: MatchProfile = {
  userSkills: [],
  userLanguages: [],
  userFrameworks: [],
  userDomains: [],
  userDifficultyLevel: "easy",
  userAvailableHoursPerWeek: 4,
  preferredContributionTypes: ["documentation", "bug", "tests"],
};

export const DEFAULT_OPTIONS: MatchOptions = {
  maxResults: 20,
  includeForks: false,
  minStars: 0,
  maxStars: 5000,
  preferredLabels: [...FALLBACK_LABELS],
};

export const SAMPLE_BEGINNER_PROFILE: MatchProfile = {
  userSkills: ["javascript", "react", "css", "html"],
  userLanguages: ["TypeScript", "JavaScript"],
  userFrameworks: ["React", "Next.js"],
  userDomains: ["frontend", "documentation", "ui"],
  userDifficultyLevel: "easy",
  userAvailableHoursPerWeek: 4,
  preferredContributionTypes: ["documentation", "bug", "tests"],
};

export const GITHUB_SKILL_SUGGESTIONS = [
  "javascript",
  "typescript",
  "python",
  "go",
  "rust",
  "java",
  "kotlin",
  "swift",
  "ruby",
  "php",
  "c++",
  "c#",
  "react",
  "next.js",
  "vue",
  "nuxt",
  "svelte",
  "solid",
  "angular",
  "astro",
  "remix",
  "tailwindcss",
  "css",
  "html",
  "sass",
  "node.js",
  "bun",
  "deno",
  "express",
  "fastify",
  "hono",
  "nestjs",
  "fastapi",
  "django",
  "flask",
  "rails",
  "spring",
  "laravel",
  "prisma",
  "drizzle",
  "supabase",
  "graphql",
  "trpc",
  "rest",
  "grpc",
  "postgresql",
  "mysql",
  "sqlite",
  "mongodb",
  "redis",
  "elasticsearch",
  "jest",
  "vitest",
  "playwright",
  "cypress",
  "pytest",
  "docker",
  "kubernetes",
  "terraform",
  "github actions",
  "ci/cd",
  "vite",
  "webpack",
  "rollup",
  "esbuild",
  "turborepo",
  "monorepo",
];

export const GITHUB_LANGUAGES = [
  "TypeScript",
  "JavaScript",
  "Python",
  "Go",
  "Rust",
  "Java",
  "Kotlin",
  "Swift",
  "C#",
  "C++",
  "PHP",
  "Ruby",
  "Elixir",
  "Dart",
  "Shell",
  "Scala",
  "Lua",
  "R",
];

export const GITHUB_FRAMEWORKS = [
  "React",
  "Next.js",
  "Vue",
  "Nuxt",
  "Svelte",
  "SvelteKit",
  "Astro",
  "Remix",
  "Angular",
  "Solid",
  "Node.js",
  "Express",
  "Fastify",
  "Hono",
  "NestJS",
  "FastAPI",
  "Django",
  "Flask",
  "Rails",
  "Laravel",
  "Spring",
  "Phoenix",
  "Flutter",
  "React Native",
  "Expo",
  "Tauri",
  "Electron",
  "Tailwind CSS",
  "Prisma",
  "Drizzle",
  "Supabase",
];

export const GITHUB_DOMAINS = [
  "frontend",
  "backend",
  "api",
  "cli",
  "devtools",
  "documentation",
  "testing",
  "accessibility",
  "security",
  "performance",
  "ui",
  "ux",
  "design-system",
  "database",
  "mobile",
  "desktop",
  "machine-learning",
  "ai",
  "data-science",
  "infra",
  "cloud",
  "webassembly",
  "blockchain",
  "game-dev",
  "education",
];

export const DIFFICULTY_LABELS: Record<MatchProfile["userDifficultyLevel"], string> = {
  easy: "Easy / first PR",
  medium: "Medium / some experience",
  hard: "Hard / complex change",
};

export const DIFFICULTY_PILL_CLASS: Record<"easy" | "medium" | "hard", string> = {
  easy: "border-emerald-500/40 bg-emerald-500/10 text-emerald-300",
  medium: "border-amber-500/40 bg-amber-500/10 text-amber-300",
  hard: "border-red-500/40 bg-red-500/10 text-red-300",
};

export const SCORE_TIER: Array<{ min: number; label: string; className: string }> = [
  { min: 80, label: "Strong match", className: "border-emerald-500/40 bg-emerald-500/10 text-emerald-300" },
  { min: 65, label: "Solid match", className: "border-sky-500/40 bg-sky-500/10 text-sky-300" },
  { min: 45, label: "Possible", className: "border-amber-500/40 bg-amber-500/10 text-amber-300" },
  { min: 0, label: "Weak", className: "border-zinc-500/40 bg-zinc-500/10 text-zinc-400" },
];

export function tierForScore(score: number): (typeof SCORE_TIER)[number] {
  return SCORE_TIER.find((tier) => score >= tier.min) ?? SCORE_TIER[SCORE_TIER.length - 1];
}
